Repository AlexWayfer/flame, pull requests merged in 2019-03, with the labels that each got.

#83 Update RuboCop to version 0.65.0, resolve some new offenses
  flame.gemspec
  lib/flame/application.rb
  lib/flame/controller.rb
  lib/flame/controller/path_to.rb
  lib/flame/dispatcher.rb
  lib/flame/dispatcher/routes.rb
  lib/flame/dispatcher/static.rb
  lib/flame/path.rb
  lib/flame/render.rb
  lib/flame/router/controller_finder.rb
  lib/flame/router/route.rb
  lib/flame/router/routes.rb
  lib/flame/router/routes_refine.rb
  lib/flame/validators.rb
  spec/flame_cli/new/app_spec.rb
  spec/integration/custom_spec.rb
  spec/spec_helper.rb
  spec/unit/application_spec.rb
  spec/unit/controller_spec.rb
  template/Rakefile
  template/config/puma.rb
  template/server
Labels: dependencies, rubocop

#81 Move `flame` executable and `template/` to separated gem
  .editorconfig
  bin/flame
  bin/new.rb
  bin/new/app.rb
  flame.gemspec
  lib/flame/application/config.rb
  spec/flame_cli/flame_spec.rb
  spec/flame_cli/new/app_spec.rb
  spec/flame_cli/new_spec.rb
  spec/flame_cli/spec_helper.rb
  spec/unit/application/config_spec.rb
  spec/unit/config/example2.yaml
  template/.editorconfig
  template/.gitignore
  template/.rubocop.yml
  template/Gemfile
  template/Rakefile
  template/application.rb.erb
  template/config.ru.erb
  template/config/config.rb.erb
  template/config/database.example.yml
  template/config/deploy.example.yml
  template/config/puma.rb
  template/config/sequel.rb.erb
  template/config/server.example.yml
  template/config/session.example.yml
  template/controllers/_controller.rb.erb
  template/controllers/site/_controller.rb.erb
  template/controllers/site/index_controller.rb.erb
  template/db/.keep
  template/filewatchers.yml
  template/helpers/.keep
  template/lib/.keep
  template/locales/en.yml
  template/models/.keep
  template/public/.keep
  template/server
  template/services/.keep
  template/views/.keep
  template/views/site/index.html.erb.erb
  template/views/site/layout.html.erb.erb
Labels: dependencies, enhancement

#84 Add `Request#headers` method (with Camel-Cased Hash)
  lib/flame/dispatcher/request.rb
  spec/unit/dispatcher/request_spec.rb
Labels: feature

#79 Fix Flame::Controller::Actions#inherit_actions
  lib/flame/controller/actions.rb
  spec/unit/controller_spec.rb
Labels: bug

#85 Update config for Cirrus CI
  .cirrus.yml
Labels: enhancement, tests

#86 Add Changelog
  CHANGELOG.md
Labels: documentation

#88 Add RuboCop task for Cirrus CI
  .cirrus.yml
Labels: code-climate, rubocop
